services:
  postgress:
    container_name: postgress
    # build: ./prisma
    image: dmitrywebwell/nodejs2024q3-service-postgress
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - user-defined

  nest-app:
    container_name: nest_app
    # build: ./
    image: dmitrywebwell/nest_app
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgress
    volumes:
      - app:/home/node/app
    command: sh -c "npx prisma migrate dev --name init && npm start"
    restart: always
    networks:
      - user-defined

volumes:
  app:
  db:

networks:
  user-defined:
    driver: bridge
